# Generated by Django 2.2.5 on 2020-01-13 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200113_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 14, 10, 27, 506619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 14, 10, 27, 505586, tzinfo=utc)),
        ),
    ]
