# Generated by Django 2.2.5 on 2020-01-13 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200113_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 14, 52, 35, 879833, tzinfo=utc)),
        ),
    ]
